username: "ketanvibhandik@gmail.com"
password: ""
search_url: "https://www.linkedin.com/search/results/people/?keywords=tcs&origin=SWITCH_SEARCH_VERTICAL&sid=n5("
message_template_path: "content/message.txt"